basePath: /ll
consumes:
- application/json
definitions:
  ErrRepSt:
    properties:
      error_code:
        description: Код ошибки
        type: string
        x-go-name: ErrorCode
    type: object
    x-go-package: github.com/mechta-market/limelog/internal/adapters/httpapi/rest
  LogListParsSt:
    properties:
      filter_obj:
        additionalProperties:
          type: object
        type: object
        x-go-name: FilterObj
      page:
        format: int64
        type: integer
        x-go-name: Page
      page_size:
        format: int64
        type: integer
        x-go-name: PageSize
    type: object
    x-go-package: github.com/mechta-market/limelog/internal/domain/entities
host: api.zeon.mechta.market
info:
  description: |-
    <br/><details>
    <summary>**Константы**</summary>
    ```
    # User types
    UsrTypeUndefined = 0
    UsrTypeAdmin     = 1
    ```
    </details>
  title: LimeLog API.
  version: 1.0.0
paths:
  /log/list:
    post:
      operationId: hLogList
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/LogListParsSt'
      responses:
        "200":
          $ref: '#/responses/logListRep'
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      tags:
      - log
  /profile/auth:
    post:
      operationId: hProfileAuth
      parameters:
      - in: body
        name: Body
        schema:
          properties:
            password:
              type: string
              x-go-name: Password
          type: object
      responses:
        "200":
          $ref: '#/responses/profileAuthRep'
        "400":
          $ref: '#/responses/errRep'
      summary: Авторизация.
      tags:
      - profile
produces:
- application/json
responses:
  errRep:
    description: ""
    schema:
      $ref: '#/definitions/ErrRepSt'
  logListRep:
    description: ""
    schema:
      properties:
        page:
          format: int64
          type: integer
          x-go-name: Page
        page_size:
          format: int64
          type: integer
          x-go-name: PageSize
        results:
          items:
            additionalProperties:
              type: object
            type: object
          type: array
          x-go-name: Results
        total_count:
          format: int64
          type: integer
          x-go-name: TotalCount
      type: object
  profileAuthRep:
    description: ""
    schema:
      properties:
        token:
          type: string
          x-go-name: Token
      type: object
schemes:
- https
- http
securityDefinitions:
  BearerToken:
    description: 'Пример: `Authorization: Bearer 2cf24dba5fb0a30e26e83b2`'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
