name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: rendau
      IMAGE: limelog
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - name: Docker build
        run: |
          docker build -t ghcr.io/$OWNER/$IMAGE:latest .

      - name: Docker push
        run: |
          docker push ghcr.io/$OWNER/$IMAGE:latest
