name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: mechta-market
      IMAGE: limelog
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u=json_key -p='${{  secrets.CR_YANDEX_PASSWORD }}' cr.yandex

      - name: Build Docker image
        run: docker build -t cr.yandex/${{  secrets.CR_YANDEX_ID }}/$IMAGE:latest .

      - name: Docker push
        run: docker push cr.yandex/${{  secrets.CR_YANDEX_ID }}/$IMAGE:latest
